namespace SIUnits {
    public enum UnitType {
    Mass = 0,
    Length = 1,
    Time = 2,
    Substance = 3,
    ElectricalCurrent = 4,
    ThermodynamicTemperature = 5,
    LuminousIntensity = 6,
    Volume = 7,
    Area = 8,
    Velocity = 9,
    Acceleration = 10,
    Force = 11,
    Energy = 12,
    CatalyticActivity = 13,
    ElectricCharge = 14,
    CelsiusTemperature = 15,
    Illuminance = 16,
    Pressure = 17,
    Power = 18,
    MagneticFlux = 19,
    Capacitance = 20,
    LuminousFlux = 21,
    AbsorbedDose = 22,
    Activity = 23,
    Inductance = 24,
    Voltage = 25,
    Resistance = 26,
    SolidAngle = 27,
    DoseEquivalent = 28,
    Frequency = 29,
    MagneticFluxDensity = 30,
    Conductance = 31,
    PlaneAngle = 32,
    DigitalStorage = 33,
    DataTransferRate = 34
  }

}
